lugares = ['Noruega', 'Roma', 'Suecia', 'UK', 'Islandia']
print('Lista orden original: ',lugares)
print('-----------------------------------------------')
x = sorted(lugares)
print('Lista orden alfabetico: ',x)
print('-----------------------------------------------')
x = sorted(lugares, reverse=True)
print('Lista orden alfabetico inverso: ',x)
print('-----------------------------------------------')
lugares.reverse()
print('Lista en reversa: ',lugares)
print('-----------------------------------------------')
lugares.reverse()
print(lugares, 'volver a imprimir:')
lugares.reverse()
print('Orden de la lista original a su orden inicial:',lugares)
print('-----------------------------------------------')
lugares.sort()
print(lugares)
print('-----------------------------------------------')
lugares.sort(reverse=True)
print(lugares)