print("Ingrese valor para x: ")
x = int(input())
print("Ingrese valor para y: ")
y = int(input())
print("Ingrese valor para n: ")
n = float(input())
print("Ingrese valor para m: ")
m = float(input())
suma1 = (x+y)
print('La suma de "x" y "y" es igual a: ' + str(suma1))
resta1 = (x-y)
print('La resta de "x" y "y" es igual a: ' + str(resta1))
producto1 = (x*y)
print('El producto de "x" y "y" es igual a: ' + str(producto1))
cosiente1 = (x/y)
print('El cosiente de "x" y "y" es igual a: ' + str(cosiente1))
residuo1 = (x%y)
print('El residuo de "x" y "y" es igual a: ' + str(residuo1))
print("--------------------------------------------------")
suma2 = (n+m)
print('La suma de "x" y "y" es igual a: ' + str(suma2))
resta2 = (n+m)
print('La resta de "x" y "y" es igual a: ' + str(resta2))
producto2 = (n*m)
print('El producto de "x" y "y" es igual a: ' + str(producto2))
cosiente2 = (n/m)
print('El cosiente de "x" y "y" es igual a: ' + str(cosiente2))
residuo2 = (n%m)
print('El residuo de "x" y "y" es igual a: ' + str(residuo2))


